In [1]:
import numpy as np

In [25]:
#creating a 1D array from a list
myarr=np.array([2,32,4,2,23]) 
print(myarr.dtype)

int32


In [11]:
myarr


array([ 2, 32,  4,  2, 23])

In [13]:
myarr=np.array([2,32,4,2,23],np.int64)

In [14]:
print(myarr.dtype)

int64


In [17]:
myarr.shape

(5,)

In [19]:
myarr[1]

32

In [26]:
#creating a 2D array from a list
arr2=np.array([[32,43,65,7,43,23]]) #2d array with 1 row & 6 columns
arr2.shape

(1, 6)

In [21]:
arr2.dtype

dtype('int32')

In [23]:
arr2[0,0]  #zeroth row oth column 

32

In [24]:
arr2[0,4]

43

## Array creation from other python structures

In [27]:
listarr=np.array([[12,3,45,32],[12,2,34,2],[45,32,45,2]])

In [28]:
listarr

array([[12,  3, 45, 32],
       [12,  2, 34,  2],
       [45, 32, 45,  2]])

In [29]:
listarr.shape

(3, 4)

In [30]:
listarr.size

12

In [33]:
# converting a tuple into array
tuplearr=np.array((3,4,5,2,2))
tuplearr

array([3, 4, 5, 2, 2])

In [35]:
zeros=np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
#creating a numpy array from a range
nprange=np.arange(14)
nprange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [40]:
#linspace - creating an equally spaced array specified within range & numbers
lspace=np.linspace(1,10,20)
lspace
#this will print 20 equally spaced numbers from 1 to 10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [41]:
ide=np.identity(10)
ide
# this will print a 10 x 10 identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
ide.shape

(10, 10)

In [43]:
arr1=np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
arr1.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
arr1.reshape(4,23)

ValueError: cannot reshape array of size 100 into shape (4,23)

In [47]:
arr1=arr1.reshape(4,25)

In [48]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
arr1.ravel()  #Return a flattened array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
arr1.shape

(4, 25)

In [53]:
arr1=arr1.ravel()
arr1.shape

(100,)

In [54]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [56]:
arr2=np.array(x)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
arr2.sum(axis=0)  # axis 0 is considered as row 

array([12,  8,  9])

In [58]:
arr2.sum(axis=1)

array([ 6, 15,  8])

In [60]:
arr2.T  # transpose of a matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [61]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
for i in arr2:
    print(i)

[1 2 3]
[4 5 6]
[7 1 0]


In [63]:
for i in arr2.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [64]:
arr2.ndim

2

In [65]:
arr2.nbytes

36

In [77]:
ar=np.array([1,2,23,7,34,54,3,5,56,5,71,46,8,5,4])

In [72]:
ar.argmax()  # this will give the index at which number is max

10

In [73]:
ar.argmin()

0

In [78]:
ar.argsort()

array([ 0,  1,  6, 14,  7,  9, 13,  3, 12,  2,  4, 11,  5,  8, 10],
      dtype=int64)

In [79]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
arr2.argmax()  # first it makes it flat and then give the index of max num

6

In [82]:
arr2.argmin()

8

In [83]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [84]:
arr2.argmax(axis=0)  # in first row at 3rd position & in 

array([2, 1, 1], dtype=int64)

In [85]:
arr2.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [86]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
arr1=np.array([[1, 0, 2],
       [6, 3, 1],
       [4, 1, 2]])

In [92]:
arr1+arr2   # this will do the addition of matrix

array([[ 2,  2,  5],
       [10,  8,  7],
       [11,  2,  2]])

In [91]:
[23,12]+[6,56]  # in list + extends the list

[23, 12, 6, 56]

In [93]:
arr1*arr2

array([[ 1,  0,  6],
       [24, 15,  6],
       [28,  1,  0]])

In [94]:
np.sqrt(arr1)

array([[1.        , 0.        , 1.41421356],
       [2.44948974, 1.73205081, 1.        ],
       [2.        , 1.        , 1.41421356]])

In [95]:
arr1

array([[1, 0, 2],
       [6, 3, 1],
       [4, 1, 2]])

In [96]:
arr1.sum()

20

In [98]:
arr1.min()

0

In [100]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [103]:
np.where(arr2>4)

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [104]:
arr2.itemsize

4

In [105]:
arr2.size

9

In [107]:
arr2.tolist()  # will convert array to list

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [109]:
l1=[1, 2, 3]
l2=[7, 1, 0]

l1+l2

[1, 2, 3, 7, 1, 0]

In [110]:
l3=np.array(l1)+np.array(l2)
l3

array([8, 3, 3])

Numpy array & attributes :
    https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html